dmp/data_loader/urls.py
from django.conf.urls import url
from data_loader.views import *
from data_loader.views.postgresql import PostgreSQLDataSourceCreateView, PostgreSQLDataSourceUpdateView
from data_loader.views.vertica import VerticaDataSourceCreateView, VerticaDataSourceUpdateView
from data_loader.views.jdbc import JDBCDataSourceCreateView, JDBCDataSourceUpdateView
from data_loader.views.mongodb import MongoDBDataSourceCreateView, MongoDBDataSourceUpdateView
from data_loader.views.ftp import FTPDataSourceCreateView, FTPDataSourceUpdateView
from data_loader.views.oracledb import OracleDBDataSourceCreateView, OracleDBDataSourceUpdateView
from data_loader.views.salesforce import SalesforceDataSourceCreateView, SalesforceDataSourceUpdateView
from data_loader.views.hadoop import HadoopDataSourceCreateView, HadoopDataSourceUpdateView
from data_loader.views.googlecloud import GoogleCloudDataSourceCreateView, GoogleCloudDataSourceUpdateView
from data_loader.views.marketo import MarketoDataSourceCreateView, MarketoDataSourceUpdateView
from data_loader.views.twitter import TwitterDataSourceCreateView, TwitterDataSourceUpdateView
from data_loader.views.dynamodb import DynamoDBDataSourceCreateView, DynamoDBDataSourceUpdateView
from data_loader.views.http import HTTPDataSourceCreateView, HTTPDataSourceUpdateView
from data_loader.views.zendesk import ZendeskDataSourceCreateView, ZendeskDataSourceUpdateView
from data_loader.views.amazons3 import AmazonS3DataSourceCreateView, AmazonS3DataSourceUpdateView
from data_loader.views.redshift import RedshiftDataSourceCreateView, RedshiftDataSourceUpdateView
from data_loader.views.mysql import MySQLDataSourceCreateView, MySQLDataSourceUpdateView
from data_loader.views.jira import JiraDataSourceCreateView, JiraDataSourceUpdateView
from data_loader.views.mssql import MSSQLDataSourceCreateView, MSSQLDataSourceUpdateView
from data_loader.views.mixpanel import MixpanelDataSourceCreateView, MixpanelDataSourceUpdateView
from data_loader.views.teradata import TeradataDataSourceCreateView, TeradataDataSourceUpdateView
from data_loader.views.sftp import SFTPDataSourceCreateView, SFTPDataSourceUpdateView
from data_loader.views.adwords import AdwordsDataSourceCreateView, AdwordsDataSourceUpdateView
from data_loader.views.sparkpost import SparkPostDataSourceCreateView, SparkPostDataSourceUpdateView

urlpatterns = [
    url(r'^$', DataSourceListView.as_view(), name='datasource-list'),

    url(r'analytics-create/(?P<provider_id>[0-9]+)/$', AnalyticsDataSourceCreateView.as_view(),
        name='analytics-datasource-create'),
    url(r'analytics-update/(?P<pk>[0-9]+)/$', AnalyticsDataSourceUpdateView.as_view(),
        name='analytics-datasource-update'),

    url(r'spreadsheets-create/(?P<provider_id>[0-9]+)/$', SpreadsheetsDataSourceCreateView.as_view(),
        name='spreadsheets-datasource-create'),
    url(r'spreadsheets-update/(?P<pk>[0-9]+)/$', SpreadsheetsDataSourceUpdateView.as_view(),
        name='spreadsheets-datasource-update'),

    url(r'postgresql-create/(?P<provider_id>[0-9]+)/$', PostgreSQLDataSourceCreateView.as_view(),
        name='postgres-datasource-create'),
    url(r'postgresql-update/(?P<pk>[0-9]+)/$', PostgreSQLDataSourceUpdateView.as_view(),
        name='postgres-datasource-update'),

    url(r'salesforce-create/(?P<provider_id>[0-9]+)/$', SalesforceDataSourceCreateView.as_view(),
        name='salesforce-datasource-create'),
    url(r'salesforce-update/(?P<pk>[0-9]+)/$', SalesforceDataSourceUpdateView.as_view(),
        name='salesforce-datasource-update'),

    url(r'amazon-create/(?P<provider_id>[0-9]+)/$', AmazonS3DataSourceCreateView.as_view(),
        name='amazon-datasource-create'),
    url(r'amazon-update/(?P<pk>[0-9]+)/$', AmazonS3DataSourceUpdateView.as_view(),
        name='amazon-datasource-update'),

    url(r'marketo-create/(?P<provider_id>[0-9]+)/$', MarketoDataSourceCreateView.as_view(),
        name='marketo-datasource-create'),
    url(r'marketo-update/(?P<pk>[0-9]+)/$', MarketoDataSourceUpdateView.as_view(),
        name='marketo-datasource-update'),

    url(r'mysql-create/(?P<provider_id>[0-9]+)/$', MySQLDataSourceCreateView.as_view(),
        name='mysql-datasource-create'),
    url(r'mysql-update/(?P<pk>[0-9]+)/$', MySQLDataSourceUpdateView.as_view(),
        name='mysql-datasource-update'),

    url(r'googlecloud-create/(?P<provider_id>[0-9]+)/$', GoogleCloudDataSourceCreateView.as_view(),
        name='googlecloud-datasource-create'),
    url(r'googlecloud-update/(?P<pk>[0-9]+)/$', GoogleCloudDataSourceUpdateView.as_view(),
        name='googlecloud-datasource-update'),

    url(r'redshift-create/(?P<provider_id>[0-9]+)/$', RedshiftDataSourceCreateView.as_view(),
        name='redshift-datasource-create'),
    url(r'redshift-update/(?P<pk>[0-9]+)/$', RedshiftDataSourceUpdateView.as_view(),
        name='redshift-datasource-update'),

    url(r'jdbc-create/(?P<provider_id>[0-9]+)/$', JDBCDataSourceCreateView.as_view(),
        name='jdbc-datasource-create'),
    url(r'jdbc-update/(?P<pk>[0-9]+)/$', JDBCDataSourceUpdateView.as_view(),
        name='jdbc-datasource-update'),

    url(r'hadoop-create/(?P<provider_id>[0-9]+)/$', HadoopDataSourceCreateView.as_view(),
        name='hadoop-datasource-create'),
    url(r'hadoop-update/(?P<pk>[0-9]+)/$', HadoopDataSourceUpdateView.as_view(),
        name='hadoop-datasource-update'),

    url(r'mixpanel-create/(?P<provider_id>[0-9]+)/$', MixpanelDataSourceCreateView.as_view(),
        name='mixpanel-datasource-create'),
    url(r'mixpanel-update/(?P<pk>[0-9]+)/$', MixpanelDataSourceUpdateView.as_view(),
        name='mixpanel-datasource-update'),

    url(r'mongodb-create/(?P<provider_id>[0-9]+)/$', MongoDBDataSourceCreateView.as_view(),
        name='mongodb-datasource-create'),
    url(r'mongodb-update/(?P<pk>[0-9]+)/$', MongoDBDataSourceUpdateView.as_view(),
        name='mongodb-datasource-update'),

    url(r'http-create/(?P<provider_id>[0-9]+)/$', HTTPDataSourceCreateView.as_view(),
        name='http-datasource-create'),
    url(r'http-update/(?P<pk>[0-9]+)/$', HTTPDataSourceUpdateView.as_view(),
        name='http-datasource-update'),

    url(r'jira-create/(?P<provider_id>[0-9]+)/$', JiraDataSourceCreateView.as_view(),
        name='jira-datasource-create'),
    url(r'jira-update/(?P<pk>[0-9]+)/$', JiraDataSourceUpdateView.as_view(),
        name='jira-datasource-update'),

    url(r'oracledb-create/(?P<provider_id>[0-9]+)/$', OracleDBDataSourceCreateView.as_view(),
        name='oracledb-datasource-create'),
    url(r'oracledb-update/(?P<pk>[0-9]+)/$', OracleDBDataSourceUpdateView.as_view(),
        name='oracledb-datasource-update'),

    url(r'zendesk-create/(?P<provider_id>[0-9]+)/$', ZendeskDataSourceCreateView.as_view(),
        name='zendesk-datasource-create'),
    url(r'zendesk-update/(?P<pk>[0-9]+)/$', ZendeskDataSourceUpdateView.as_view(),
        name='zendesk-datasource-update'),

    url(r'mssql-create/(?P<provider_id>[0-9]+)/$', MSSQLDataSourceCreateView.as_view(),
        name='mssql-datasource-create'),
    url(r'mssql-update/(?P<pk>[0-9]+)/$', MSSQLDataSourceUpdateView.as_view(),
        name='mssql-datasource-update'),

    url(r'sftp-create/(?P<provider_id>[0-9]+)/$', SFTPDataSourceCreateView.as_view(),
        name='sftp-datasource-create'),
    url(r'sftp-update/(?P<pk>[0-9]+)/$', SFTPDataSourceUpdateView.as_view(),
        name='sftp-datasource-update'),

    url(r'ftp-create/(?P<provider_id>[0-9]+)/$', FTPDataSourceCreateView.as_view(),
        name='ftp-datasource-create'),
    url(r'ftp-update/(?P<pk>[0-9]+)/$', FTPDataSourceUpdateView.as_view(),
        name='ftp-datasource-update'),

    url(r'dynamodb-create/(?P<provider_id>[0-9]+)/$', DynamoDBDataSourceCreateView.as_view(),
        name='dynamodb-datasource-create'),
    url(r'dynamodb-update/(?P<pk>[0-9]+)/$', DynamoDBDataSourceUpdateView.as_view(),
        name='dynamodb-datasource-update'),



    url(r'vertica-create/(?P<provider_id>[0-9]+)/$', VerticaDataSourceCreateView.as_view(),
        name='vertica-datasource-create'),
    url(r'vertica-update/(?P<pk>[0-9]+)/$', VerticaDataSourceUpdateView.as_view(),
        name='vertica-datasource-update'),

    url(r'twitter-create/(?P<provider_id>[0-9]+)/$', TwitterDataSourceCreateView.as_view(),
        name='twitter-datasource-create'),
    url(r'twitter-update/(?P<pk>[0-9]+)/$', TwitterDataSourceUpdateView.as_view(),
        name='twitter-datasource-update'),

    url(r'teradata-create/(?P<provider_id>[0-9]+)/$', TeradataDataSourceCreateView.as_view(),
        name='teradata-datasource-create'),
    url(r'teradata-update/(?P<pk>[0-9]+)/$', TeradataDataSourceUpdateView.as_view(),
        name='teradata-datasource-update'),

    url(r'adwords-create/(?P<provider_id>[0-9]+)/$', AdwordsDataSourceCreateView.as_view(),
        name='adwords-datasource-create'),
    url(r'adwords-update/(?P<pk>[0-9]+)/$', AdwordsDataSourceUpdateView.as_view(),
        name='adwords-datasource-update'),

    url(r'sparkpost-create/(?P<provider_id>[0-9]+)/$', SparkPostDataSourceCreateView.as_view(),
        name='sparkpost-datasource-create'),
    url(r'sparkpost-update/(?P<pk>[0-9]+)/$', SparkPostDataSourceUpdateView.as_view(),
        name='sparkpost-datasource-update'),


    url(r'create/(?P<provider_id>[0-9]+)/$', DataSourceCreateView.as_view(), name='datasource-create'),
    url(r'update/(?P<pk>[0-9]+)/$', DataSourceUpdateView.as_view(), name='datasource-update'),
    url(r'delete/(?P<pk>[0-9]+)/$', DataSourceDeleteView.as_view(), name='datasource-delete'),
    url(r'data-providers/$', DataProviderListView.as_view(), name='datasource-providers'),
    url(r'settings/$', DataFlowSettingsUpdateView.as_view(), name='datasource-settings')
]

dmp/dmp/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from data_loader.views import DataSourceListView


urlpatterns = [
    url(r'^$', DataSourceListView.as_view(), name='index'),
    url(r'^customer/', include('customer.urls', namespace="customer")),
    url(r'^data-sources/', include('data_loader.urls', namespace="data_loader")),
]
urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

dmp/data_loader/models.py
import os
import codecs
from django.db import models
from django.contrib.auth.models import User
from customer.models import Customer
from django.conf import settings
import ruamel.yaml as yaml


class DataProvider(models.Model):
    title = models.CharField('Provider Title', max_length=255, blank=True, default="Google Analytics")
    name = models.CharField('Provider Name', max_length=255, blank=True, default="Google Analytics")
    order = models.IntegerField('Provider ordering in list', blank=True, default=999)


class DataSource(models.Model):
    user = models.ForeignKey(Customer)
    name = models.CharField('Data Source Name', max_length=255, default=None)
    data_provider = models.ForeignKey(DataProvider, null=True)
    created_at = models.DateTimeField('Created at', auto_now_add=True)

    class Meta:
        verbose_name = 'Data source'
        verbose_name_plural = 'Data source'

    def get_configs_base_path(self):
        return os.path.join(settings.BASE_DIR, self._meta.app_label, 'embulk_configs')

    def check_provider_configs_path(self):
        path = os.path.join(self.get_configs_base_path(), 'providers', self.data_provider.name)
        if not os.path.exists(path):
            os.makedirs(path)
        return path

    def check_config_template_path(self):
        template_path = os.path.join(self.get_configs_base_path(), 'config_templates', 'template.yml')
        if os.path.exists(template_path):
            return template_path

    def get_config_template_content(self):
        template = self.check_config_template_path()
        with codecs.open(template, 'r', 'utf-8') as fi:
            template_data = yaml.round_trip_load(fi, preserve_quotes=True)
        return template_data

    def write_config_content(self, path, template_data):
        fname = os.path.join(path, "config_{user_id}_{data_source_id}.yml".format(user_id=self.user_id,
                                                                                  data_source_id=self.id))
        with codecs.open(fname, 'w', 'utf-8') as yaml_file:
            yaml_file.write(yaml.round_trip_dump(template_data, block_seq_indent=True))
        return fname

    def create_config_file(self):
        return self.write_config_content(self.check_provider_configs_path(), self.get_config_template_content())


class AnalyticsDataSource(DataSource):
    data_source = models.OneToOneField(DataSource)
    account_id = models.CharField('Account ID', max_length=255, default=None)
    upload_file = models.FileField('Upload file', upload_to='file_uploads', default=None)
    # document_url = models.CharField('Document URL', max_length=355, default=None, blank=True, null=True)
    dimensions = models.CharField('Analytics dimensions', max_length=355, blank=True, null=True)
    metrics = models.CharField('Analytics metrics', max_length=355, blank=True, null=True)

    class Meta:
        verbose_name = 'Google Analytics Data source'
        verbose_name_plural = 'Google Analytics Data source'

    def filename(self):
        return os.path.basename(self.upload_file.name)

    def update_config_content_for_analytics(self, template_data):
        from django.conf import settings
        with codecs.open(os.path.join(settings.MEDIA_ROOT, self.upload_file.name), 'r', 'utf-8') as key_file:
            key_data = key_file.read()
        template_data['in']['json_key_content'] = key_data
        template_data['in']['view_id'] = self.account_id
        template_data['out']['table'] = "{}_{}".format(self.data_provider.name, self.account_id)
        return template_data

    def create_config_file(self):
        template_content = self.get_config_template_content()
        template_content = self.update_config_content_for_analytics(template_content)
        return self.write_config_content(self.check_provider_configs_path(), template_content)


class DataFlowSettings(models.Model):
    TIME_INTERVALS = ((1, '5 minutes'),
                      (2, '30 minutes'),
                      (3, '1 hour'),
                      (4, '2 hours'),
                      (5, '5 hours'),
                      (6, '10 hours'),
                      (7, '24 hours'))
    user = models.ForeignKey(Customer)
    sync_interval = models.SmallIntegerField(choices=TIME_INTERVALS, default=2)

dmp/data_loader/models/adwords.py
import os
from django.db import models
from .models import DataSource


class AdwordsDataSource(DataSource):
    data_source = models.OneToOneField(DataSource)
    conditions = models.CharField('Query condition list', max_length=255, blank=True, null=True)
    field_list = models.CharField('Field list to query', max_length=255)
    date_range = models.CharField('Date range', max_length=255)
    report_type = models.CharField('Report type', max_length=255)
    oauth_key_file = models.FileField('OAuth2 keyfile', upload_to='file_uploads', default=None)

    class Meta:
        verbose_name = 'Adwords Data source'
        verbose_name_plural = 'Adwords Data sources'

    def filename(self):
        return os.path.basename(self.oauth_key_file.name)

    def create_config_file(self):
        pass

    def update_config_file(self):
        pass

dmp/data_loader/models/amazons3.py
from django.db import models
from .models import DataSource


class AmazonS3DataSource(DataSource):
    data_source = models.OneToOneField(DataSource)
    bucket = models.CharField('S3 bucket name', max_length=255)
    path_prefix = models.CharField('Path prefix', max_length=255)
    access_key = models.CharField('Access key', max_length=255)
    secret_key = models.CharField('Secret key', max_length=255)
    endpoint = models.CharField('Endpoint URL', max_length=255)

    class Meta:
        verbose_name = 'AmazonS3 Data source'
        verbose_name_plural = 'AmazonS3 Data sources'

    def create_config_file(self):
        pass

    def update_config_file(self):
        pass

dmp/data_loader/models/dynamobd.py
import os
from django.db import models
from .models import DataSource


class DynamoDBDataSource(DataSource):
    data_source = models.OneToOneField(DataSource)
    host = models.CharField('Host', max_length=255)
    port = models.CharField('Port', max_length=255)
    access_key = models.CharField('Access key', max_length=255)
    secret_key = models.CharField('Secret key', max_length=255)
    database = models.CharField('Database name', max_length=255)
    region = models.CharField('Region name', max_length=255)
    endpoint = models.CharField('Endpoint URl', max_length=255)
    table = models.CharField('Table name', max_length=255)

    class Meta:
        verbose_name = 'DynamoDB Data source'
        verbose_name_plural = 'DynamoDB Data sources'

    def create_config_file(self):
        pass

    def update_config_file(self):
        pass

dmp/data_loader/models/ftp.py
from django.db import models
from .models import DataSource


class FTPDataSource(DataSource):
    data_source = models.OneToOneField(DataSource)
    host = models.CharField('Host', max_length=255)
    port = models.CharField('Port', max_length=255)
    username = models.CharField('Username', max_length=255)
    password = models.CharField('Password', max_length=255)
    prefix = models.CharField('Database', max_length=255)

    class Meta:
        verbose_name = 'FTP Data source'
        verbose_name_plural = 'FTP Data sources'

    def create_config_file(self):
        pass

    def update_config_file(self):
        pass

dmp/data_loader/templates/datasource/data_providers_list.html
{% extends 'layout.html' %}
{% block content %}

    <div class="page datasources-select">
        <div class="page-title">
            <div class="content">
                <h1>Add Data Source</h1>
                <div class="page-title-actions">
                    <a href="javascript:void(0);" class="button button-green">Add Data Source</a>
                </div>
            </div>
        </div>
        <div class="page-content">
            <div class="content">
                <div class="page-supplements">
                    <div class="row">
                        <div class="col col-33">
                            <div class="search">
                                <input type="text" class="search-input form-input" placeholder="Search..." />
                                <span class="fa fa-search"></span>
                            </div>
                        </div>
                        <div class="col col-33">
                            <div class="switches">
                                <a href="javascript:void(0);"  class="switch switch-active">All</a>
                                <a href="javascript:void(0);"  class="switch">Popular</a>
                                <a href="javascript:void(0);"  class="switch">APIs</a>
                                <a href="javascript:void(0);"  class="switch">Databases</a>
                            </div>
                        </div>
                        <div class="col col-33">
                            <a href="javascript:void(0);"  class="pseudolink">My data source is not in the list</a>
                        </div>
                    </div>
                </div>
                <div class="box datasources-select">
                    <ul>
                        {% for provider in object_list %}
                            <li>
                                <a href="{% url provider.get_add_url_name provider_id=provider.pk %}" class="button button-outline">
                                    <span class="icon icon-{{ provider.name }}"></span>{{ provider.title }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

dmp/data_loader/templates/datasource/datasource_create.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block page_script %}
<script src="{% static "js/datasource_crud.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}

    <div class="page datasources-add">
        <div class="page-title">
            <div class="content">
                <h1>{% if form.instance.pk %}Update{% else %}Add{% endif %} Data Source - {{ provider.name }}</h1>
            </div>
        </div>

        <div class="page-content">
            <div class="content">

                <div class="box">
                    <div class="form-note">
                        <span class="fa fa-lock"></span>
                        All sensitive information is encrypted before stored
                    </div>
                    <div class="row">
                        <div class="col col-50">
                            <form id="form-create" method="POST" action="" enctype="multipart/form-data">
                                    {% for error in form.non_field_errors %}
                                        <p class="errors">{{ error }}</p>
                                    {% endfor %}
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-label">Data Source Name:</div>
                                    {% for error in form.name.errors %}
                                        <p class="errors">{{ error }}</p>
                                    {% endfor %}
                                    {{ form.name }}
                                </div>
                                <div class="form-row">
                                    <div class="form-label">{% if provider.name == "spreadsheets" %}Worksheet ID{% else %}View ID:{% endif %}</div>
                                    {% for error in form.account_id.errors %}
                                        <p class="errors">{{ error }}</p>
                                    {% endfor %}
                                    {{ details_form.account_id }}
                                </div>
                                <div class="form-row">
                                    <div class="form-label">Private Key:</div>
                                    {% for error in form.upload_file.errors %}
                                        <p class="errors">{{ error }}</p>
                                    {% endfor %}
                                    <div class="form-file">
                                        <span id="file-text-lable" class="form-placeholder"> Upload file...</span>
                                        {{ form.upload_file }}
                                    </div>

                                </div>
                                <div class="form-buttons">
{#                                    <a href="#" class="button button-gray">Preview</a>#}
                                    <a href="javascript:void(0);" onclick="document.getElementById('form-create').submit(); return false;" class="button button-green">{% if form.instance.pk %}Update{% else %}Save & Collect{% endif %}</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dmp/data_loader/templates/datasource/datasource_list.html
{% extends 'layout.html' %}
{%  block content %}


    <div class="page datasources">
        <div class="page-title">
            <div class="content">
                <h1>Data Sources</h1>
                <div class="page-title-actions">
                    <a href="{% url "data_loader:datasource-providers" %}" class="button button-green">Add Data Source</a>
                </div>
            </div>
        </div>
        <div class="page-content">
            <div class="content">
                <div class="page-supplements">
                    <div class="row">
                        <div class="col col-33">
                            <div class="search">
                                <input type="text" class="search-input form-input" placeholder="Search..." />
                                <span class="fa fa-search"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box datasources-list">
                    {% if messages %}
                        {% for message in messages %}
                          <span class="{{ message.tags }}">{{ message }}</span>
                        {% endfor %}
                    {% endif %}
                    <table cellspacing="0" class="datasources-table">
                        {% for datasource in object_list %}
                            <tr>
                                <td class="datasources-table-name"><span class="icon icon-{{ datasource.data_provider.name }}"></span>{{ datasource.name }}</td>
                                <td class="datasources-type">{{ datasource.data_provider.title}}</td>
                                <td class="datasources-actions">
                                    <span class="ds-info">{{ datasource.id }}</span>
                                    <a href="{% url datasource.get_update_url_name pk=datasource.pk %}" class="button button-action"><span class="fa fa-pencil"></span></a>
                                    <a href="javascript:void(0);" onclick="document.getElementById('delete-form-{{ datasource.pk }}').submit(); return false;"  class="button button-action">
                                        <form id="delete-form-{{ datasource.pk }}" action="{% url "data_loader:datasource-delete" pk=datasource.pk %}" method ="post">
                                            {% csrf_token %}
                                            <span class="fa fa-trash"></span>
                                        </form>
                                    </a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td class="datasources-table-name">You haven't added any entries yet</td>
                                <td class="datasources-type"></td>
                                <td class="datasources-actions">
                                </td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

dmp/data_loader/templates/datasource/datasource_update.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block page_script %}
<script src="{% static "js/datasource_crud.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}

    <div class="page datasources-add">
        <div class="page-title">
            <div class="content">
                <h1>Edit Data Source</h1>
            </div>
        </div>

        <div class="page-content">
            <div class="content">

                <div class="box">
                    <div class="form-note">
                        <span class="fa fa-lock"></span>
                        All sensitive information is encrypted before stored
                    </div>
                    <div class="row">
                        <div class="col col-50">
                            <form id="form-create" method="POST" action="" enctype="multipart/form-data">
                                    {% for error in form.non_field_errors %}
                                        <p class="errors">{{ error }}</p>
                                    {% endfor %}
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-label">Data Source Name:</div>
                                    {% for error in form.name.errors %}
                                        <p class="errors">{{ error }}</p>
                                    {% endfor %}
                                    {{ form.name }}
                                </div>
                                <div class="form-row">
                                    <div class="form-label">View ID:</div>
                                    {% for error in form.account_id.errors %}
                                        <p class="errors">{{ error }}</p>
                                    {% endfor %}
                                    {{ form.account_id }}
                                </div>
                                <div class="form-row">
                                    <div class="form-label">Private Key:</div>
                                    {% for error in form.upload_file.errors %}
                                        <p class="errors">{{ error }}</p>
                                    {% endfor %}
                                    <div class="form-file">
                                        <span id="file-text-lable" class="form-placeholder">{% if form.instance.filename %} {{ form.instance.filename }} {% else %} Upload file...{% endif %}</span>
                                        {{ form.upload_file }}
                                    </div>

                                </div>
                                <div class="form-buttons">
{#                                    <a href="#" class="button button-gray">Preview</a>#}
                                    <a href="javascript:void(0);" onclick="document.getElementById('form-create').submit(); return false;" class="button button-green">Update & Collect</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}